[package]
name = "lenna_core"
version = "0.1.0"
authors = ["Christian <chriamue@gmail.com>"]
edition = "2018"
description = "Lenna Core Library"
license = "MIT"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["python"]
python = ["ndarray", "ndarray-image", "numpy", "pyo3", "pythonize"]

[dependencies]
dyn-clone = "1.0.4"
image = { version = "0.23.12", default-features = false, features = ["png"] }
imageproc = "0.22.0"
paste = "1.0"
pyo3 = {version = "0.13.0", features = ["extension-module"], optional = true }
ndarray = { version = "0.14", optional = true }
ndarray-image = { version = "0.3.0", optional = true }
numpy = {version = "0.13.0", optional = true }
pythonize = { version = "0.13.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[build-dependencies]
rustc_version = "0.3"

[package.metadata.maturin]
classifiers = ["Programming Language :: Python"]
requires-dist = ["numpy"]
