name: Rust Test and Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  benchmark:
    name: Run tests and benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install just
        uses: extractions/setup-just@v1
        with:
          just-version: "1.39"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "benchmark-cache"
          cache-directories: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Check formatting
        run: just fmt

      - name: Run lints
        run: just lint

      - name: Run tests
        run: just test

      - name: Run benchmarks
        run: just bench
        env:
          CARGO_TERM_COLOR: always

      - name: Check dependencies
        run: just deny

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ github.sha }}
          path: |
            ./target/criterion/**/*.json
            ./target/criterion/**/*.svg
          if-no-files-found: error
          retention-days: 90

      - name: Download previous benchmark data
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          path: prev-benchmark
          name: benchmark-results-${{ github.event.before }}
